import { Meditation } from '../types';

export const MEDITATION_LIBRARY: Meditation[] = [
  {
    id: 'med_solar_heart',
    title: 'Solar Heart Resonance',
    description: 'Direct the astral golden light into the cardiac plexus. Harmonize sovereign martial courage with deep inner stillness.',
    durationMinutes: 10,
    associatedPlanet: 'Sun / Thagirion',
    focusArchetype: 'Inner Daemon & Golden Core',
    breathingPattern: 'Box (4-4-4-4)',
    mantra: 'IAO SABAO THERION',
  },
  {
    id: 'med_lunar_abyss',
    title: 'Abyss Descent into Gamaliel',
    description: 'Enter the nocturnal lunar tides. Unwind deep tension from the autonomic nervous system and cultivate boundless fluid perception.',
    durationMinutes: 15,
    associatedPlanet: 'Moon / Gamaliel',
    focusArchetype: 'Nocturnal Astral Tide',
    breathingPattern: 'Void (4-7-8)',
    mantra: 'LILITH ABISHA NAAMAH',
  },
  {
    id: 'med_iron_root_mabu',
    title: 'Iron Root Ma Bu Stillness',
    description: 'Channel gravitational force through the feet into the earth. Transform skeletal weight into impenetrable rooting density.',
    durationMinutes: 12,
    associatedPlanet: 'Saturn / Satariel',
    focusArchetype: 'Impenetrable Skeletal Fortress',
    breathingPattern: 'Deep (5-5-5-5)',
    mantra: 'AGIOS O KAPH SATARIEL',
  },
  {
    id: 'med_fire_golachab',
    title: 'Flaming Sphere of Golachab',
    description: 'Ignite the lower dantian furnace. Awaken dynamic kinetic strike readiness while maintaining razor-calm mental focus.',
    durationMinutes: 8,
    associatedPlanet: 'Mars / Golachab',
    focusArchetype: 'Martial Kinetic Climax',
    breathingPattern: 'Fire (2-1-2-1)',
    mantra: 'ZAZAS NASATANADA GOLACHAB',
  },
  {
    id: 'med_caduceus_breath',
    title: 'Hermetic Caduceus Breath',
    description: 'Weave the dual currents of Ida and Pingala along the central spinal column. Sharpen synaptic speed and perceptual latency.',
    durationMinutes: 10,
    associatedPlanet: 'Mercury / Samael',
    focusArchetype: 'Neural Caduceus Transmission',
    breathingPattern: 'Box (4-4-4-4)',
    mantra: 'TAPHATHARATH SAMAEL OROBAS',
  },
  {
    id: 'med_silk_reeling_venus',
    title: 'Silk Reeling Fascial Harmony',
    description: 'Dissolve residual torque in the joints. Fortify the connective fascia through soft continuous circular respiration.',
    durationMinutes: 14,
    associatedPlanet: 'Venus / A\'arab Zaraq',
    focusArchetype: 'Elastic Sinew & Fascial Armor',
    breathingPattern: 'Deep (5-5-5-5)',
    mantra: 'ASTARTE BAAL-ZEPHON AARAB',
  },
];
