import { TarotCard, DrawnCard } from '../types';

export const TAROT_DECK: TarotCard[] = [
  // MAJOR ARCANA (0-21)
  {
    id: 'MAJOR_0',
    name: 'The Fool',
    imagePath: '00-TheFool.png',
    suit: 'Major',
    uprightMeaning: 'New beginnings, spiritual spontaneity, leap into the primordial void.',
    reversedMeaning: 'Recklessness, fear of initiation, foolish naivety.',
    associatedPlanetOrSign: 'Uranus / Air',
    glyph: '♅',
  },
  {
    id: 'MAJOR_1',
    name: 'The Magician',
    imagePath: '01-TheMagician.png',
    suit: 'Major',
    uprightMeaning: 'Direct will, elemental manifestation, channel of the four tools.',
    reversedMeaning: 'Deception, blocked channel, scattered kinetic focus.',
    associatedPlanetOrSign: 'Mercury',
    glyph: '☿',
  },
  {
    id: 'MAJOR_2',
    name: 'The High Priestess',
    imagePath: '02-TheHighPriestess.png',
    suit: 'Major',
    uprightMeaning: 'Lunar subconscious, veil of Isis, hidden esoteric currents.',
    reversedMeaning: 'Secrets, repressed intuition, surface superficiality.',
    associatedPlanetOrSign: 'Moon',
    glyph: '☽',
  },
  {
    id: 'MAJOR_3',
    name: 'The Empress',
    imagePath: '03-TheEmpress.png',
    suit: 'Major',
    uprightMeaning: 'Abundance, generative matrix, sensual organic vitality.',
    reversedMeaning: 'Creative stagnation, over-indulgence, barren soil.',
    associatedPlanetOrSign: 'Venus',
    glyph: '♀',
  },
  {
    id: 'MAJOR_4',
    name: 'The Emperor',
    imagePath: '04-TheEmperor.png',
    suit: 'Major',
    uprightMeaning: 'Sovereign authority, iron structure, unyielding centerline posture.',
    reversedMeaning: 'Tyranny, rigidity, loss of physical grounding.',
    associatedPlanetOrSign: 'Aries',
    glyph: '♈',
  },
  {
    id: 'MAJOR_5',
    name: 'The Hierophant',
    imagePath: '05-TheHierophant.png',
    suit: 'Major',
    uprightMeaning: 'Esoteric transmission, traditional lineage, sacred keys.',
    reversedMeaning: 'Dogma, blind orthodoxy, rebellious awakening.',
    associatedPlanetOrSign: 'Taurus',
    glyph: '♉',
  },
  {
    id: 'MAJOR_6',
    name: 'The Lovers',
    imagePath: '06-TheLovers.png',
    suit: 'Major',
    uprightMeaning: 'Alchemical marriage, sacred polarity, unified will.',
    reversedMeaning: 'Internal disharmony, conflicting paths, severance.',
    associatedPlanetOrSign: 'Gemini',
    glyph: '♊',
  },
  {
    id: 'MAJOR_7',
    name: 'The Chariot',
    imagePath: '07-TheChariot.png',
    suit: 'Major',
    uprightMeaning: 'Triumphant vector, disciplined momentum, conquering sphinxes.',
    reversedMeaning: 'Loss of control, catastrophic derailment, blind aggression.',
    associatedPlanetOrSign: 'Cancer',
    glyph: '♋',
  },
  {
    id: 'MAJOR_8',
    name: 'Strength',
    imagePath: '08-Strength.png',
    suit: 'Major',
    uprightMeaning: 'Internal fortitude, mastering the beast, soft power overcoming hard steel.',
    reversedMeaning: 'Self-doubt, explosive uncontrolled rage, weakness in stance.',
    associatedPlanetOrSign: 'Leo',
    glyph: '♌',
  },
  {
    id: 'MAJOR_9',
    name: 'The Hermit',
    imagePath: '09-TheHermit.png',
    suit: 'Major',
    uprightMeaning: 'Inner lantern of truth, solitude, contemplation of the abyss.',
    reversedMeaning: 'Paralyzing isolation, withdrawal from reality, closed mind.',
    associatedPlanetOrSign: 'Virgo',
    glyph: '♍',
  },
  {
    id: 'MAJOR_10',
    name: 'Wheel of Fortune',
    imagePath: '10-WheelOfFortune.png',
    suit: 'Major',
    uprightMeaning: 'Cosmic cycles, karma in motion, inevitable ascending turn.',
    reversedMeaning: 'Resisting the cycle, temporary setback, stagnation.',
    associatedPlanetOrSign: 'Jupiter',
    glyph: '♃',
  },
  {
    id: 'MAJOR_11',
    name: 'Justice',
    imagePath: '11-Justice.png',
    suit: 'Major',
    uprightMeaning: 'Equilibrium, karmic precision, unwavering blade of truth.',
    reversedMeaning: 'Biased judgment, dishonesty, unbalanced kinetic vectors.',
    associatedPlanetOrSign: 'Libra',
    glyph: '♎',
  },
  {
    id: 'MAJOR_12',
    name: 'The Hanged Man',
    imagePath: '12-TheHangedMan.png',
    suit: 'Major',
    uprightMeaning: 'Sacred suspension, inverted vision, surrender for wisdom.',
    reversedMeaning: 'Stalling, needless martyrdom, resisting sacrifice.',
    associatedPlanetOrSign: 'Neptune / Water',
    glyph: '♆',
  },
  {
    id: 'MAJOR_13',
    name: 'Death',
    imagePath: '13-Death.png',
    suit: 'Major',
    uprightMeaning: 'Profound metamorphosis, death of the old self, regeneration.',
    reversedMeaning: 'Clinging to dead forms, fear of transmutation, decay.',
    associatedPlanetOrSign: 'Scorpio',
    glyph: '♏',
  },
  {
    id: 'MAJOR_14',
    name: 'Temperance',
    imagePath: '14-Temperance.png',
    suit: 'Major',
    uprightMeaning: 'Alchemical blending, fluid harmony, patient distillation.',
    reversedMeaning: 'Imbalance, extremes, disharmonious breath rhythm.',
    associatedPlanetOrSign: 'Sagittarius',
    glyph: '♐',
  },
  {
    id: 'MAJOR_15',
    name: 'The Devil',
    imagePath: '15-TheDevil.png',
    suit: 'Major',
    uprightMeaning: 'Shadow confrontation, raw chthonic drive, breaking illusions.',
    reversedMeaning: 'Severing chains, liberation from illusion, awakening.',
    associatedPlanetOrSign: 'Capricorn',
    glyph: '♑',
  },
  {
    id: 'MAJOR_16',
    name: 'The Tower',
    imagePath: '16-TheTower.png',
    suit: 'Major',
    uprightMeaning: 'Sudden lightning awakening, shattering of false ego structures.',
    reversedMeaning: 'Averting disaster, internal collapse, delayed reckoning.',
    associatedPlanetOrSign: 'Mars',
    glyph: '♂',
  },
  {
    id: 'MAJOR_17',
    name: 'The Star',
    imagePath: '17-TheStar.png',
    suit: 'Major',
    uprightMeaning: 'Astral illumination, pure hope, divine celestial pouring.',
    reversedMeaning: 'Despair, clouded vision, disconnected from stellar guidance.',
    associatedPlanetOrSign: 'Aquarius',
    glyph: '♒',
  },
  {
    id: 'MAJOR_18',
    name: 'The Moon',
    imagePath: '18-TheMoon.png',
    suit: 'Major',
    uprightMeaning: 'Dream illusions, gateway to the subconscious, astral beasts.',
    reversedMeaning: 'Release of fear, dispelling mist, piercing deception.',
    associatedPlanetOrSign: 'Pisces',
    glyph: '♓',
  },
  {
    id: 'MAJOR_19',
    name: 'The Sun',
    imagePath: '19-TheSun.png',
    suit: 'Major',
    uprightMeaning: 'Solar radiance, absolute vitality, triumphant clarity.',
    reversedMeaning: 'Temporary burnout, dim light, false optimism.',
    associatedPlanetOrSign: 'Sun',
    glyph: '☉',
  },
  {
    id: 'MAJOR_20',
    name: 'Judgement',
    imagePath: '20-Judgement.png',
    suit: 'Major',
    uprightMeaning: 'Astral awakening, resurrection of the true self, trumpet call.',
    reversedMeaning: 'Self-doubt, ignoring the inner calling, stagnation.',
    associatedPlanetOrSign: 'Pluto / Fire',
    glyph: '♇',
  },
  {
    id: 'MAJOR_21',
    name: 'The World',
    imagePath: '21-TheWorld.png',
    suit: 'Major',
    uprightMeaning: 'Cosmic completion, ouroboros wholeness, master of the four realms.',
    reversedMeaning: 'Incomplete cycle, lack of closure, seeking shortcuts.',
    associatedPlanetOrSign: 'Saturn / Earth',
    glyph: '♄',
  },

  // MINOR ARCANA HIGHLIGHTS
  {
    id: 'WANDS_1',
    name: 'Ace of Wands',
    imagePath: 'Wands01.png',
    suit: 'Wands',
    uprightMeaning: 'Primordial spark of martial will, explosive creative energy.',
    reversedMeaning: 'Delayed action, misdirected strike power.',
    associatedPlanetOrSign: 'Fire / Mars',
    glyph: '🜂',
  },
  {
    id: 'WANDS_6',
    name: 'Six of Wands',
    imagePath: 'Wands06.png',
    suit: 'Wands',
    uprightMeaning: 'Victory, martial acclaim, triumph over opponents.',
    reversedMeaning: 'Hubris, fall from grace, hollow glory.',
    associatedPlanetOrSign: 'Jupiter in Leo',
    glyph: '🜂',
  },
  {
    id: 'CUPS_1',
    name: 'Ace of Cups',
    imagePath: 'Cups01.png',
    suit: 'Cups',
    uprightMeaning: 'Overflowing spiritual Grail, pure emotional & intuitive fountain.',
    reversedMeaning: 'Blocked emotions, drained vitality.',
    associatedPlanetOrSign: 'Water / Neptune',
    glyph: '🜄',
  },
  {
    id: 'SWORDS_1',
    name: 'Ace of Swords',
    imagePath: 'Swords01.png',
    suit: 'Swords',
    uprightMeaning: 'Razor mental clarity, unclouded insight, sword of sovereign truth.',
    reversedMeaning: 'Cruelty, chaotic intellect, destructive thought patterns.',
    associatedPlanetOrSign: 'Air / Mercury',
    glyph: '🜁',
  },
  {
    id: 'PENTACLES_1',
    name: 'Ace of Pentacles',
    imagePath: 'Pentacles01.png',
    suit: 'Pentacles',
    uprightMeaning: 'Rooted physical manifestation, iron body density, tangible wealth.',
    reversedMeaning: 'Financial loss, unstable physical footing.',
    associatedPlanetOrSign: 'Earth / Saturn',
    glyph: '🜃',
  },
  {
    id: 'PENTACLES_10',
    name: 'Ten of Pentacles',
    imagePath: 'Pentacles10.png',
    suit: 'Pentacles',
    uprightMeaning: 'Generational legacy, ancestral stronghold, indestructible foundation.',
    reversedMeaning: 'Disputed inheritance, crumbling stability.',
    associatedPlanetOrSign: 'Mercury in Virgo',
    glyph: '🜃',
  },
];

export function getRandomTarotCards(count: number): DrawnCard[] {
  const positions = count === 1 
    ? ['Core Cosmic Guidance'] 
    : count === 3 
    ? ['Past Matrix // Root Origin', 'Present Vector // Active Cross', 'Future Horizon // Telos']
    : ['Origin', 'Obstacle', 'Hidden Current', 'Environment', 'Ultimate Climax'];

  const shuffled = [...TAROT_DECK].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map((card, idx) => ({
    card,
    isReversed: Math.random() < 0.35,
    positionName: positions[idx] || `Vector ${idx + 1}`,
  }));
}

export function synthesizeTarotGuidance(drawn: DrawnCard): string {
  const orient = drawn.isReversed ? 'REVERSED' : 'UPRIGHT';
  const meaning = drawn.isReversed ? drawn.card.reversedMeaning : drawn.card.uprightMeaning;
  return `Archetype [${drawn.card.name.toUpperCase()} • ${orient}] resonates under cosmic current of ${drawn.card.associatedPlanetOrSign}. Key transmission: ${meaning}`;
}
